import type { Metadata } from "next";
import "./globals.css";
import { Comfortaa } from "next/font/google";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* bg-gradient-to-b from-blue-100 to-white */}
      <body
        className={`antialiased ${comfortaa.variable} ${comfortaa.className} min-h-screen bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
